created by curosor ai
vxa-niikawa/actions pull request #1
Opened 2024-05-30 08:34 UTC by vxa-niikawa

test actions 1

2024-05-30 08:44 UTC, vxa-niikawa reviewed
存在しないカラムを指定している箇所をコメントアウトする必要がある。

2024-05-30 09:34 UTC, niikawa requested changes
修正してください。

2024-05-30 10:21 UTC, niikawa requested changes
テストコードが存在しません。

2024-05-31 06:36 UTC, niikawa approved these changes

2024-05-31 06:37 UTC, merged